export const CHECK_BOOKMARKED_BEGIN = "CHECK_BOOKMARKED_BEGIN"
export const CHECK_BOOKMARKED_SUCCESS = "CHECK_BOOKMARKED_SUCCESS"
export const CHECK_BOOKMARKED_FAILED = "CHECK_BOOKMARKED_FAILED"

export const PSUH_POST_TO_BOOKMARK_BEGIN = "PSUH_POST_TO_BOOKMARK_BEGIN"
export const PSUH_POST_TO_BOOKMARK_SUCCESS = "PSUH_POST_TO_BOOKMARK_SUCCESS"
export const PSUH_POST_TO_BOOKMARK_FAILED = "PSUH_POST_TO_BOOKMARK_FAILED"

export const POP_POST_FROM_BOOKMARK_BEGIN = "POP_POST_FROM_BOOKMARK_BEGIN"
export const POP_POST_FROM_BOOKMARK_SUCCESS = "POP_POST_FROM_BOOKMARK_SUCCESS"
export const POP_POST_FROM_BOOKMARK_FAILED = "POP_POST_FROM_BOOKMARK_FAILED"

export const FETCH_BOOKMARK_BEGIN = "FETCH_BOOKMARK_BEGIN"
export const FETCH_BOOKMARK_SUCCESS = "FETCH_BOOKMARK_SUCCESS"
export const FETCH_BOOKMARK_FAILED = "FETCH_BOOKMARK_FAILED"