export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN"
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
export const CREATE_POST_FAILED = "CREATE_POST_FAILED"

export const REMOVE_POST_BEGIN = ""
export const REMOVE_POST_SUCCESS = ""
export const REMOVE_POST_FAILED = ""


export const UNLOCK_POST_BEGIN = "UNLOCK_POST_BEGIN"
export const UNLOCK_POST_SUCCESS = "UNLOCK_POST_SUCCESS"
export const UNLOCK_POST_FAILED = "UNLOCK_POST_FAILED"

export const FETCH_POST_BY_AUTHOR_BEGIN = "FETCH_POST_BY_AUTHOR_BEGIN"
export const FETCH_POST_BY_AUTHOR_SUCCESS = "FETCH_POST_BY_AUTHOR_SUCCESS"
export const FETCH_POST_BY_AUTHOR_FAILED = "FETCH_POST_BY_AUTHOR_FAILED"


export const FETCH_UNLOCK_POST_BEGIN = "UNLOCK_POST_BEGIN"
export const FETCH_UNLOCK_POST_SUCCESS = "UNLOCK_POST_SUCCESS"
export const FETCH_UNLOCK_POST_FAILED = "UNLOCK_POST_FAILED"

/**
 * GET ALL POST
 */
export const FETCH_ALL_POST_BEGIN = "FETCH_ALL_POST_BEGIN"
export const FETCH_ALL_POST_SUCCESS = "FETCH_ALL_POST_SUCCESS"
export const FETCH_ALL_POST_FAILED = "FETCH_ALL_POST_FAILED"



export const FETCH_POST_BEGIN = "FETCH_POST_BEGIN"
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS"
export const FETCH_POST_FAILED = "FETCH_POST_FAILED"
