export const FOLLOW_BEGIN = "FOLLOW_BEGIN"
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS"
export const FOLLOW_FAILED = "FOLLOW_FAILED"


export const UNFOLLOW_BEGIN = "UNFOLLOW_BEGIN"
export const UNFOLLOW_SUCCESS = "UNFOLLOW_SUCCESS"
export const UNFOLLOW_FAILED = "UNFOLLOW_FAILED"

export const FETCH_FOLLOWERS_BEGIN = "FETCH_FOLLOWERS_BEGIN"
export const FETCH_FOLLOWERS_SUCCESS = "FETCH_FOLLOWERS_SUCCESS"
export const FETCH_FOLLOWERS_FAILED = "FETCH_FOLLOWERS_FAILED"


export const FETCH_FOLLOWING_BEGIN = "FETCH_FOLLOWING_BEGIN"
export const FETCH_FOLLOWING_SUCCESS = "FETCH_FOLLOWING_SUCCESS"
export const FETCH_FOLLOWING_FAILED = "FETCH_FOLLOWING_FAILED"


export const CHECK_IS_FOLLOWED_BEGIN = "CHECK_IS_FOLLOWED_BEGIN"
export const CHECK_IS_FOLLOWED_SUCCESS = "CHECK_IS_FOLLOWED_SUCCESS"
export const CHECK_IS_FOLLOWED_FAILED = "CHECK_IS_FOLLOWED_FAILED"


