export const FOLLOW_USER_BEGIN = "FOLLOW_USER_BEGIN"
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS"
export const FOLLOW_USER_FAILED = "FOLLOW_USER_FAILED"


export const UNFOLLOW_USER_BEGIN = "UNFOLLOW_USER_BEGIN"
export const UNFOLLOW_USER_SUCCESS = "UNFOLLOW_USER_SUCCESS"
export const UNFOLLOW_USER_FAILED = "UNFOLLOW_USER_FAILED"

export const FETCH_FOLLOWERS_BEGIN = "FETCH_FOLLOWERS_BEGIN"
export const FETCH_FOLLOWERS_SUCCESS = "FETCH_FOLLOWERS_SUCCESS"
export const FETCH_FOLLOWERS_FAILED = "FETCH_FOLLOWERS_FAILED"


export const FETCH_FOLLOWING_BEGIN = "FETCH_FOLLOWING_BEGIN"
export const FETCH_FOLLOWING_SUCCESS = "FETCH_FOLLOWING_SUCCESS"
export const FETCH_FOLLOWING_FAILED = "FETCH_FOLLOWING_FAILED"


export const CHECK_IS_FOLLOWED_USER_BEGIN = "CHECK_IS_FOLLOWED_USER_BEGIN"
export const CHECK_IS_FOLLOWED_USER_SUCCESS = "CHECK_IS_FOLLOWED_USER_SUCCESS"
export const CHECK_IS_FOLLOWED_USER_FAILED = "CHECK_IS_FOLLOWED_USER_FAILED"


