export const FETCH_PROFILE_USER_BEGIN = "FETCH_PROFILE_USER_BEGIN"
export const FETCH_PROFILE_USER_SUCCESS = "FETCH_PROFILE_USER_SUCCESS"
export const FETCH_PROFILE_USER_FAILED= "FETCH_PROFILE_USER_FAILED"