export const CREATE_COMMENT_BEGIN = 'CREATE_COMMENT_BEGIN'
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS"
export const CREATE_COMMENT_FAILED = "CREATE_COMMENT_FAILED"
export const REMOVE_COMMENT_BEGIN  ='REMOVE_COMMENT_BEGIN'
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS'
export const REMOVE_COMMENT_FAILED = 'REMOVE_COMMENT_FAILED'

export const FETCH_ALL_COMMENT_BEGIN = "FETCH_ALL_COMMENT_BEGIN"
export const FETCH_ALL_COMMENT_SUCCESS = 'FETCH_ALL_COMMENT_SUCCESS'
export const FETCH_ALL_COMMENT_FAILED = 'FETCH_ALL_COMMENT_FAILED'