export const CREATE_SERIES_BEGIN = "CREATE_SERIES_BEGIN"
export const CREATE_SERIES_SUCCESS = "CREATE_SERIES_SUCCESS"
export const CREATE_SERIES_FAILED = "CREATE_SERIES_FAILED"

export const FETCH_SERIES_BEGIN = "FETCH_SERIES_BEGIN"
export const FETCH_SERIES_SUCCESS = "FETCH_SERIES_SUCCESS"
export const FETCH_SERIES_FAILED = "FETCH_SERIES_FAILED"
