export const FETCH_NOTIFY_MESSAGE_BEGIN = "FETCH_NOTIFY_MESSAGE_BEGIN"
export const FETCH_NOTIFY_MESSAGE_SUCCESS = "FETCH_NOTIFY_MESSAGE_SUCCESS"
export const FETCH_NOTIFY_MESSAGE_FAILED = "FETCH_NOTIFY_MESSAGE_FAILED"

export const COUNT_UNREAD_NOTIFY_MESSAGE_BEGIN = "COUNT_UNREAD_NOTIFY_MESSAGE_BEGIN"
export const COUNT_UNREAD_NOTIFY_MESSAGE_SUCCESS = "COUNT_UNREAD_NOTIFY_MESSAGE_SUCCESS"
export const COUNT_UNREAD_NOTIFY_MESSAGE_FAILED = "COUNT_UNREAD_NOTIFY_MESSAGE_FAILED"

export const READ_NOTIFY_MESSAGE_BEGIN = "READ_NOTIFY_MESSAGE_BEGIN"
export const READ_NOTIFY_MESSAGE_SUCCESS = "READ_NOTIFY_MESSAGE_SUCCESS"
export const READ_NOTIFY_MESSAGE_FAILED = "READ_NOTIFY_MESSAGE_FAILED"

export const READ_ALL_NOTIFY_MESSAGE_BEGIN = "READ_ALL_NOTIFY_MESSAGE_BEGIN"
export const READ_ALL_NOTIFY_MESSAGE_SUCCESS = "READ_ALL_NOTIFY_MESSAGE_SUCCESS"
export const READ_ALL_NOTIFY_MESSAGE_FAILED = "READ_ALL_NOTIFY_MESSAGE_FAILED"
