export const UPDATE_SETTING_NOTIFY_BEGIN = "UPDATE_SETTING_NOTIFY_BEGIN"
export const UPDATE_SETTING_NOTIFY_SUCCESS = "UPDATE_SETTING_NOTIFY_SUCCESS"
export const UPDATE_SETTING_NOTIFY_END = "UPDATE_SETTING_NOTIFY_END"

export const FETCH_SETTING_BEGIN = "FETCH_SETTING_BEGIN"
export const FETCH_SETTING_SUCCESS = "FETCH_SETTING_SUCCESS"
export const FETCH_SETTING_END = "FETCH_SETTING_END"