export const REPORT_BEGIN = "REPORT_BEGIN"
export const REPORT_SUCCESS = "REPORT_SUCCESS"
export const REPORT_FALIED = "REPORT_FALIED"

export const FETCH_LIST_REPORT_BEGIN = "FETCH_LIST_REPORT_BEGIN"
export const FETCH_LIST_REPORT_SUCCESS = "FETCH_LIST_REPORT_SUCCESS"
export const FETCH_LIST_REPORT_FALIED = "FETCH_LIST_REPORT_FALIED"