export  const CREATE_PAYMENT_URL_BEGIN = 'CREATE_PAYMENT_URL_BEGIN'
export  const CREATE_PAYMENT_URL_SUCCESS = 'CREATE_PAYMENT_URL_SUCCESS'
export  const CREATE_PAYMENT_URL_FAILED = 'CREATE_PAYMENT_URL_FAILED'


export  const FETCH_FLOWER_BEGIN  = 'FETCH_FLOWER_BEGIN'
export  const FETCH_FLOWER_SUCCESS = 'FETCH_FLOWER_SUCCESS'
export  const FETCH_FLOWER_FAILED = 'FETCH_FLOWER_FAILED'
