export  const CREATE_PAYMENT_URL_BEGIN = 'CREATE_PAYMENT_URL_BEGIN'
export  const CREATE_PAYMENT_URL_SUCCESS = 'CREATE_PAYMENT_URL_SUCCESS'
export  const CREATE_PAYMENT_URL_FAILED = 'CREATE_PAYMENT_URL_FAILED'
